name: demo
on:

  push:
    branches: ["main"]
    
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu_latest
    
    steps:
     - name: Run hello world
       run: echo "hello world"
    

  
